# This file contains the HTTP requests to interact with Tracks (tracksapp).
@baseUrl = http://localhost:8000
@username = mbedded
@password = mbedded

### Get all contexts
GET {{baseUrl}}/contexts.xml
Authorization: Basic {{username}} {{password}}

### Get tasks for context
GET {{baseUrl}}/contexts/1/todos.xml
Authorization: Basic {{username}} {{password}}

### Get active tasks for context
GET {{baseUrl}}/contexts/1/todos.xml?limit_to_active_todos=1
Authorization: Basic {{username}} {{password}}

### Create context
POST {{baseUrl}}/contexts.xml
Authorization: Basic {{username}} {{password}}
Content-Type: text/xml

<context>
  <name>New context</name>
</context>

### Delete context
DELETE {{baseUrl}}/contexts/1.xml
Authorization: Basic {{username}} {{password}}



### Get all tasks
GET {{baseUrl}}/todos.xml
Authorization: Basic {{username}} {{password}}

### Get active tasks
GET {{baseUrl}}/todos.xml?limit_to_active_todos=1
Authorization: Basic {{username}} {{password}}

### Get one task
GET {{baseUrl}}/todos/1.xml
Authorization: Basic {{username}} {{password}}

### Toggle task
PUT {{baseUrl}}/todos/1/toggle_check.xml
Authorization: Basic {{username}} {{password}}

### Create task
POST {{baseUrl}}/todos.xml
Authorization: Basic {{username}} {{password}}
Content-Type: text/xml

<todo>
  <description>My new todo</description>
  <context-id>1</context-id>
  <notes>Some text
line 2 text</notes>
</todo>

### Delete task
DELETE {{baseUrl}}/todos/1.xml
Authorization: Basic {{username}} {{password}}

### Update task
PUT {{baseUrl}}/todos/1.xml
Authorization: Basic {{username}} {{password}}
Content-Type: text/xml

<todo>
  <description>Updated description</description>
  <context-id>1</context-id>
  <notes>Updated notes</notes>
</todo>
